version: "3.8"

services:
  r1:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_r1
    container_name: r1
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    networks:
      net12:
        ipv4_address: 20.20.1.2

  r2:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_r2
    container_name: r2
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    networks:
      net12:
        ipv4_address: 20.20.1.3
      net23:
        ipv4_address: 30.30.1.2

  r3:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_r3
    container_name: r3
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    networks:
      net23:
        ipv4_address: 30.30.1.3

  app:
    build: .
    container_name: bgp-leak-app
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - r1
      - r2
      - r3
    networks:
      - net12
      - net23

networks:
  net12:
    driver: bridge
    ipam:
      config:
        - subnet: 20.20.1.0/24

  net23:
    driver: bridge
    ipam:
      config:
        - subnet: 30.30.1.0/24
